Development
senseexcel/ser-engine-rest pull request #14
Opened 2019-03-18 14:05 UTC by mossbeard

New Rest Engine Service
I need a nuget package

2019-03-19 13:04 UTC, konne requested changes
@mossbeard please rework

2019-03-19 13:04 UTC, konne commented on src/Attributes/ValidateModelStateAttribute.cs
> +            if (Boolean.TryParse(value, out var boolResult))
häääää

this should work if (Boolean.TryParse(value, out var boolResult)
                               return boolResult;

2019-03-19 13:04 UTC, konne commented on src/Attributes/ValidateModelStateAttribute.cs
> +                return Convert.ChangeType(value, typeof(bool));
reject -> INVARIANT CULTURE ???!!!!???

2019-03-19 13:04 UTC, konne commented on src/Controllers/FileOperations.cs
> +                var msg = $"The Method {nameof(UploadWithId)} failed.";
don't repeat yourself, use Methods

2019-03-19 13:04 UTC, konne commented on src/Controllers/FileOperations.cs
> +                logger.Trace($"{nameof(Upload)} - Response: {JsonConvert.SerializeObject(result)}");
same here Method ReturnObjectAndTraceToNLog(...)

2019-03-19 13:04 UTC, konne commented on src/Controllers/TaskOperations.cs
> +                logger.Trace($"{nameof(CreateTaskWithId)} - Response: {JsonConvert.SerializeObject(result)}");
same again, use helper Method

2019-03-19 13:04 UTC, konne commented on src/Controllers/TaskOperations.cs
> +                var msg = $"The Method {nameof(CreateTaskWithId)} failed.";
same here

2019-03-19 13:04 UTC, konne commented on src/Dockerfile
> +FROM microsoft/dotnet:2.1-sdk AS build
MISSING 2.2

2019-03-19 13:04 UTC, konne commented on src/Filters/OpenApiDocumentFilter.cs
> +                    var basePath = serverUri?.PathAndQuery?.Split('?')?.FirstOrDefault() ?? null;
Uri.Query / QueryBuilder / Parser

2019-03-19 13:04 UTC, konne commented on src/Program.cs
> +                .SetBasePath(AppContext.BaseDirectory)
Indent

2019-03-19 13:04 UTC, konne commented on src/SerEngineRest.xml
> +<?xml version="1.0"?>
if this is agenrated file -> gitignore !!!

2019-03-19 13:04 UTC, konne commented on src/Services/ReportingService.cs
> +            if (id.HasValue)
if you have id -> pick id -> fill folders with Array with one element -> default code

2019-03-19 13:04 UTC, konne commented on src/Services/ReportingService.cs
> +                if (taskId.HasValue)
same as before

2019-03-19 13:04 UTC, konne commented on src/Startup.cs
> +                        options.DescribeAllEnumsAsStrings();
try fluent way

2019-03-19 13:04 UTC, konne commented on src/ser-engine-rest.csproj
> +    <PackageReference Include="System.Drawing.Common" Version="4.5.1" />
if this is in the engine I think you don't need it here

2019-03-19 13:04 UTC, konne commented on src/ser-engine-rest.xml
> +<?xml version="1.0"?>
same-> autogenerated remove from git

2019-03-19 13:04 UTC, konne commented on src/wwwroot/README.md
> +# Welcome to ASP.NET 5 Preview
NOP

2019-03-19 13:04 UTC, konne commented on src/wwwroot/index.html
> +<meta http-equiv="refresh" content="0;URL='./swagger/'" />
?? possible with kestrel config / redirect of routes?

2019-03-19 13:04 UTC, konne commented on src/wwwroot/web.config
> +<?xml version="1.0" encoding="utf-8"?>
please google if remove is possible

2019-03-20 06:23 UTC, mossbeard commented
@konne 
I have adjusted all comments now.
The "options" variable in the startup.cs can only be called individually.
Comment "try fluent way"

2019-03-20 12:40 UTC, konne approved these changes
@mossbeard please merge

2019-03-20 12:45 UTC, merged